<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit2fa5dc26edca8c54bfedf31e43545972
{
    public static $files = array (
        '320cde22f66dd4f5d3fd621d3e88b98f' => __DIR__ . '/..' . '/symfony/polyfill-ctype/bootstrap.php',
    );

    public static $prefixLengthsPsr4 = array (
        'S' => 
        array (
            'Symfony\\Polyfill\\Ctype\\' => 23,
        ),
        'D' => 
        array (
            'Dotenv\\' => 7,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Symfony\\Polyfill\\Ctype\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/polyfill-ctype',
        ),
        'Dotenv\\' => 
        array (
            0 => __DIR__ . '/..' . '/vlucas/phpdotenv/src',
        ),
    );

    public static $prefixesPsr0 = array (
        'S' => 
        array (
            'SEOstats\\' => 
            array (
                0 => __DIR__ . '/..' . '/seostats/seostats',
            ),
        ),
        'P' => 
        array (
            'PhpOption\\' => 
            array (
                0 => __DIR__ . '/..' . '/phpoption/phpoption/src',
            ),
        ),
    );

    public static $classMap = array (
        'GTB_Exception' => __DIR__ . '/..' . '/seostats/seostats/SEOstats/Services/3rdparty/GTB_PageRank.php',
        'GTB_Helper' => __DIR__ . '/..' . '/seostats/seostats/SEOstats/Services/3rdparty/GTB_PageRank.php',
        'GTB_PageRank' => __DIR__ . '/..' . '/seostats/seostats/SEOstats/Services/3rdparty/GTB_PageRank.php',
        'GTB_Request' => __DIR__ . '/..' . '/seostats/seostats/SEOstats/Services/3rdparty/GTB_PageRank.php',
        'GTB_awesomeHash' => __DIR__ . '/..' . '/seostats/seostats/SEOstats/Services/3rdparty/GTB_PageRank.php',
        'GTB_ieHash' => __DIR__ . '/..' . '/seostats/seostats/SEOstats/Services/3rdparty/GTB_PageRank.php',
        'GTB_jenkinsHash' => __DIR__ . '/..' . '/seostats/seostats/SEOstats/Services/3rdparty/GTB_PageRank.php',
        'Services_JSON' => __DIR__ . '/..' . '/seostats/seostats/SEOstats/Services/3rdparty/JSON.php',
        'Services_JSON_Error' => __DIR__ . '/..' . '/seostats/seostats/SEOstats/Services/3rdparty/JSON.php',
        'pref' => __DIR__ . '/..' . '/seostats/seostats/SEOstats/Services/3rdparty/GTB_PageRank.php',
        'tbr' => __DIR__ . '/..' . '/seostats/seostats/SEOstats/Services/3rdparty/GTB_PageRank.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit2fa5dc26edca8c54bfedf31e43545972::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit2fa5dc26edca8c54bfedf31e43545972::$prefixDirsPsr4;
            $loader->prefixesPsr0 = ComposerStaticInit2fa5dc26edca8c54bfedf31e43545972::$prefixesPsr0;
            $loader->classMap = ComposerStaticInit2fa5dc26edca8c54bfedf31e43545972::$classMap;

        }, null, ClassLoader::class);
    }
}
